### ISSUE TITLE
Проверка ДЗ1

### ISSUE THREAD

**Issue by Damovetsky** [rn7cvj/todo_list#1]
Привет! Я проверил твой код по первому заданию.
Гладко стелишь, что сказать) А если серьёзно, то мне есть чему у тебя поучиться в плане подхода к некоторым задачам.

Наверное самое близкое, к чему можно придраться, так это дизайн, который не соответствует заданной в макете цветовой палитре. Дефолтный material 3, конечно, смотрится хорошо, но есть некоторые прям явные проблемы. Например в белой теме на экранах редактирования/создания задачи у тебя поле ввода фиолетовое и тут сложно найти любителя, которому такое бы понравилось)
Я бы посоветовал выделить темы, шрифты и цветовые палитры в отдельные файлы. Цвета для палитр можно взять тут:
https://m3.material.io/theme-builder#/custom
Если установить сидом синий цвет из макета, переопределить ещё несколько цветов и поставить прозрачным surfaceTint, то должно получиться куда ближе к макету и при этом красиво.
По сути это к вёрстке относится, но баллы снять за такое у меня рука не поднимается.

Про кнопку инфо ты и сам написал, это, конечно, лучше пофиксить.

Также я бы посоветовал делать хотя бы какую-то базовую валидацию на установку задач, потому что сейчас можно пустую задачу сохранить без описания.

Но есть и относительно существенный косяк с состоянием задачи, когда работает скрытие выполненных. Дело в том, что если включить скрытие и попытаться отметить задачу свайпом, то у тебя метод toggle вызывается дважды и задача на экране воскреснет не отмеченной. Тут всё же придётся снять балл про критерию, потому что баг ломает функцию.

Таким образом расценка:
Чистота кода и общая структура проекта: 4/4
Вёрстка + навигация: 15/16 (минус балл в категории "свайп по айтему Выполнено/Удалить с логикой")
Логирование: 2/2
Иконка: пока 0/4 
По истории коммитов увидел, что ты использовал flutter_launcher_icons, а потом в следующем коммите его из зависимостей удалил. Возможно я что-то проглядел и ты потом всё же сам иконку установил. Скажи пожалуйста, если так, с указанием конкретного коммита, где ты это сделал.

А пока оценка 21/26.
Приятно было почитать твой код, многому научился, за это спасибо. Но поработай немного над темами ещё. 
И удачи тебе в последующих домашках)

**Comment by rn7cvj** [comment]
> Привет! Я проверил твой код по первому заданию. Гладко стелишь, что сказать) А если серьёзно, то мне есть чему у тебя поучиться в плане подхода к некоторым задачам.
> 
> Наверное самое близкое, к чему можно придраться, так это дизайн, который не соответствует заданной в макете цветовой палитре. Дефолтный material 3, конечно, смотрится хорошо, но есть некоторые прям явные проблемы. Например в белой теме на экранах редактирования/создания задачи у тебя поле ввода фиолетовое и тут сложно найти любителя, которому такое бы понравилось) Я бы посоветовал выделить темы, шрифты и цветовые палитры в отдельные файлы. Цвета для палитр можно взять тут: https://m3.material.io/theme-builder#/custom Если установить сидом синий цвет из макета, переопределить ещё несколько цветов и поставить прозрачным surfaceTint, то должно получиться куда ближе к макету и при этом красиво. По сути это к вёрстке относится, но баллы снять за такое у меня рука не поднимается.
> 
> Про кнопку инфо ты и сам написал, это, конечно, лучше пофиксить.
> 
> Также я бы посоветовал делать хотя бы какую-то базовую валидацию на установку задач, потому что сейчас можно пустую задачу сохранить без описания.
> 
> Но есть и относительно существенный косяк с состоянием задачи, когда работает скрытие выполненных. Дело в том, что если включить скрытие и попытаться отметить задачу свайпом, то у тебя метод toggle вызывается дважды и задача на экране воскреснет не отмеченной. Тут всё же придётся снять балл про критерию, потому что баг ломает функцию.
> 
> Таким образом расценка: Чистота кода и общая структура проекта: 4/4 Вёрстка + навигация: 15/16 (минус балл в категории "свайп по айтему Выполнено/Удалить с логикой") Логирование: 2/2 Иконка: пока 0/4 По истории коммитов увидел, что ты использовал flutter_launcher_icons, а потом в следующем коммите его из зависимостей удалил. Возможно я что-то проглядел и ты потом всё же сам иконку установил. Скажи пожалуйста, если так, с указанием конкретного коммита, где ты это сделал.
> 
> А пока оценка 21/26. Приятно было почитать твой код, многому научился, за это спасибо. Но поработай немного над темами ещё. И удачи тебе в последующих домашках)

Привет, спасибо за подробный разбор, забавно что мы проверяли код друг друга) 

По поводу иконки нам все равно разрешили использовать flutter_launcher_icons и более того если внимательно посмотришь то увидишь что я просто случайно добавил в pubspec либу и там нету нужного кода, для замены иконки, дальше идут коммиты с ручной заменой файлов

По поводу дизайна, нам разрешили его менять не упрощая верстки.

По поводу бага 👀👀👀, пасибо как-то проглядел во время тестов,

Верни пж 4 балла за иконку, тебе я их вернул 😢😢😢
