### ISSUE TITLE
Проверка ДЗ 1

### ISSUE THREAD

**Issue by Shiplayer** [rn7cvj/todo_list#2]
Привет, я проверяю твое домашнее задание.

Я смотрю на твой реализованный аппбар, и у меня возникают вопросы.
Я наблюдаю некий скачок текста при переходе в коллапс аппбара, это ожидаемо?
Явно отсутствует иконка скрытия/показа выполненных заданий в коллапс аппбаре.

Классно, что ты самостоятельно вычисляешь прогресс, для сворачивания и разворачивания аппбара. Мне кажется, что ты вполне можешь улучшить свой аппбар внимательно по исследовав виджет `FlexibleSpaceBar`, там можно найти нечто интересное)

К сожалению, замечаю, что в тексте присутствуют орфографические ошибки в названиях переменных/методов.

https://github.com/rn7cvj/todo_list/blob/4a9544fa1822a7f8caba396a94325b30058f6916/lib/pages/home_page/home_portrait.dart#L39

https://github.com/rn7cvj/todo_list/blob/4a9544fa1822a7f8caba396a94325b30058f6916/lib/pages/home_page/home_portrait.dart#L55-L89
Не очень понимаю, зачем тут нужен был отдельный метод, да еще и публичный, когда можно было сделать

```
Widget buildTaskList(BuildContext context, List<Task> tasks) {
    //Согласно заветам тз "Анимации не ожидаем."
    return AnimatedSize(
      alignment: Alignment.topCenter,
      duration: animationDurationFast,
      child: Column(
        children: [
          if (tasks.isNotEmpty) TaskTile(task: tasks.first, isFirst: true),
          if (tasks.length > 1)
            ...tasks.map((task) => TaskTile(task: task, isFirst: false)),
          if (tasks.isNotEmpty)
            const Divider(
              indent: appPaddingMedium,
              endIndent: appPaddingMedium,
              height: 0,
            )
        ],
      ),
    );
  }
```
А еще бы лучше, вынести в отдельный виджет, как и ПУБЛИЧНЫЙ метод `buildAddNewTaskButton`

https://github.com/rn7cvj/todo_list/blob/4a9544fa1822a7f8caba396a94325b30058f6916/lib/pages/home_page/widgets/task_tile.dart#L15
можно было запятую указать, чтоб при форматировании, все читалось проще.

К сожалению, я вижу, что это публичные методы и виджеты, которые собираются в методах, да еще и могут лежать в переменных, после мапа, только утяжеляет виджет, понимаю, что всё, что относится к указанному экрану разбиты на методы, но это явно же проигрывает, когда мы их выносим в виджеты. Как минимум, они все будут перерисовываться. 

Принты:
https://github.com/rn7cvj/todo_list/blob/4a9544fa1822a7f8caba396a94325b30058f6916/lib/routes.dart#L62
https://github.com/rn7cvj/todo_list/blob/4a9544fa1822a7f8caba396a94325b30058f6916/lib/routes.dart#L79

Итог:
- Чистота кода и общая структура проекта - 4 балла 
- Верстка 
-- Полностью свёрстаны 2 экрана по макетам - 10 балла
-- Свайп - 1.5 балла
-- Показ выполненных дел с логикой  - 1.5 балла (нельзя показать выполненные дела, если задач > n, так чтоб аппбар можно было свернуть)
- Разное
-- Реализовано нормальное логирование (не print'ы) - 1 балл (нашел принты в коде)
-- Есть человеческая иконка у приложения (iOS или Android) - 4 балла

22 балла

**Comment by rn7cvj** [comment]
> Привет, я проверяю твое домашнее задание.
> 
> Я смотрю на твой реализованный аппбар, и у меня возникают вопросы. Я наблюдаю некий скачок текста при переходе в коллапс аппбара, это ожидаемо? Явно отсутствует иконка скрытия/показа выполненных заданий в коллапс аппбаре.
> 
> Классно, что ты самостоятельно вычисляешь прогресс, для сворачивания и разворачивания аппбара. Мне кажется, что ты вполне можешь улучшить свой аппбар внимательно по исследовав виджет `FlexibleSpaceBar`, там можно найти нечто интересное)
> 
> К сожалению, замечаю, что в тексте присутствуют орфографические ошибки в названиях переменных/методов.
> 
> https://github.com/rn7cvj/todo_list/blob/4a9544fa1822a7f8caba396a94325b30058f6916/lib/pages/home_page/home_portrait.dart#L39
> 
> https://github.com/rn7cvj/todo_list/blob/4a9544fa1822a7f8caba396a94325b30058f6916/lib/pages/home_page/home_portrait.dart#L55-L89
> 
> 
> Не очень понимаю, зачем тут нужен был отдельный метод, да еще и публичный, когда можно было сделать
> ```
> Widget buildTaskList(BuildContext context, List<Task> tasks) {
>     //Согласно заветам тз "Анимации не ожидаем."
>     return AnimatedSize(
>       alignment: Alignment.topCenter,
>       duration: animationDurationFast,
>       child: Column(
>         children: [
>           if (tasks.isNotEmpty) TaskTile(task: tasks.first, isFirst: true),
>           if (tasks.length > 1)
>             ...tasks.map((task) => TaskTile(task: task, isFirst: false)),
>           if (tasks.isNotEmpty)
>             const Divider(
>               indent: appPaddingMedium,
>               endIndent: appPaddingMedium,
>               height: 0,
>             )
>         ],
>       ),
>     );
>   }
> ```
> 
> А еще бы лучше, вынести в отдельный виджет, как и ПУБЛИЧНЫЙ метод `buildAddNewTaskButton`
> 
> https://github.com/rn7cvj/todo_list/blob/4a9544fa1822a7f8caba396a94325b30058f6916/lib/pages/home_page/widgets/task_tile.dart#L15
> 
> 
> можно было запятую указать, чтоб при форматировании, все читалось проще.
> К сожалению, я вижу, что это публичные методы и виджеты, которые собираются в методах, да еще и могут лежать в переменных, после мапа, только утяжеляет виджет, понимаю, что всё, что относится к указанному экрану разбиты на методы, но это явно же проигрывает, когда мы их выносим в виджеты. Как минимум, они все будут перерисовываться.
> 
> Принты:
> 
> https://github.com/rn7cvj/todo_list/blob/4a9544fa1822a7f8caba396a94325b30058f6916/lib/routes.dart#L62
> 
> 
> https://github.com/rn7cvj/todo_list/blob/4a9544fa1822a7f8caba396a94325b30058f6916/lib/routes.dart#L79
> 
> Итог:
> 
> * Чистота кода и общая структура проекта - 4 балла
> * Верстка
>   -- Полностью свёрстаны 2 экрана по макетам - 10 балла
>   -- Свайп - 1.5 балла
>   -- Показ выполненных дел с логикой  - 1.5 балла (нельзя показать выполненные дела, если задач > n, так чтоб аппбар можно было свернуть)
> * Разное
>   -- Реализовано нормальное логирование (не print'ы) - 1 балл (нашел принты в коде)
>   -- Есть человеческая иконка у приложения (iOS или Android) - 4 балла
> 
> 22 балла

Привет, спасибо большое за такую подробную проверку 😊😊😊

Не понимаю за что ты снял половину баллов за свайп (задание отмечается как выполненное, удаляется, это единственные пункты) 

Так-же за "Показ выполненных дел с логикой" не понял претензии, пункт вроде бы про то чтобы работала  скрытие, показ выполненных задач, поведение аппбара не прописано в фигме в чем проблема ?) и это больше все же проблема дизайна, чем логики показы выполненных задач (пункт очень странно сформулирован в общем)

По поводу принтов, ну эти функции ни разу не вызываются они там из лекции, и к основной логике отношения не имеют, эти методы можно просто удалить. Более того пункт не про то чтобы в коде не было принтов, а чтобы вывод важной для работы информации был реализован нормально и он есть, дело конечно твое снимать ли за 2 несчастных принта которые ни разу не будут вызванные баллы, при условии что весь остальной вывод реализован нормально, но это прям дикое душнилово 😥😥😥.

В целом еще раз спасибо за подробный разбор, особенно благодарен за оценку кода, надо будет улучшать этот пункт, я понимаю претензии, но мне кажется что оценка слишком строгай, по крайне мере в вопросе первых двух пунктов(свайп и показ выполненных дел с логикой) все таки пункты очень размыты,

**Comment by rn7cvj** [comment]
> Я смотрю на твой реализованный аппбар, и у меня возникают вопросы.
> Я наблюдаю некий скачок текста при переходе в коллапс аппбара, это ожидаемо?
> Явно отсутствует иконка скрытия/показа выполненных заданий в коллапс аппбаре. 

Иконки там нету, да косяк( Ну фиксится одной строчкой и на функционал не влияет

Не понял что за скачок текста, у меня вроде все плавно, кинь issue желательно с видосом

**Comment by Shiplayer** [comment]
> По поводу принтов, ну эти функции ни разу не вызываются они там из лекции, и к основной логике отношения не имеют, эти методы можно просто удалить.

Звучит так, что код не приведен к чистоте, и весь неиспользуемый функционал не был убран? Я обращал еще внимание, что есть комментарий в коде с закомменчинным кодом.

**Comment by rn7cvj** [comment]
> > По поводу принтов, ну эти функции ни разу не вызываются они там из лекции, и к основной логике отношения не имеют, эти методы можно просто удалить.
> 
> Звучит так, что код не приведен к чистоте, и весь неиспользуемый функционал не был убран? Я обращал еще внимание, что есть комментарий в коде с закомменчинным кодом.

Звучит справедливо, но
Да забыл убрать, хотя на самом деле просто не использовал и в будущем пригодится, но влияет ли это как-то на качество логов которые есть в проекте ?

Оценка на тебе просто я не понимаю к чему так сильно занижать баллы (

**Comment by Shiplayer** [comment]
> -- Показ выполненных дел с логикой - 1.5 балла (нельзя показать выполненные дела, если задач > n, так чтоб аппбар можно было свернуть)

чисто формально, за это я могу вернуть баллы, так как кнопка то работает, если интуинтивно кликнуть в нужную область.

**Comment by Shiplayer** [comment]
Есть два бага:
https://github.com/rn7cvj/todo_list/issues/6 - тут не соответствует дизайну,
https://github.com/rn7cvj/todo_list/issues/3 - тут бага в функционале Показ выполненных дел с логикой

**Comment by rn7cvj** [comment]
> Есть два бага: #6 - тут не соответствует дизайну, #3 - тут бага в функционале Показ выполненных дел с логикой

Я понял этот пункт как возможность скрыть покзаать выполненные таски и с этим проблем нету, то что там нету кнопки косяк скорее верстки и заслуживает ли он такого штрафа ?

Дело опять же твое, но я за такие мелкие косяки снимал баллы в других менее весомых пунктах, чтобы сильно чуваков не штрафовать.

А еще там закрыли возможность ставить оценки, в общем пасибо за суровую критику (

**Comment by Shiplayer** [comment]
напиши мне в телегу @shiplayer
