### ISSUE TITLE
Проверка ДЗ 2

### ISSUE THREAD

**Issue by dslmnvv** [rn7cvj/todo_list#7]
Привет, проверяю твое дз, постараюсь максимально подробно изложить все замечания и подкрепить их документацией.

## 1. flutter_lints. 
Я вижу, что у тебя в зависимостях подтягивается flutter_lints. По умолчанию он настроен уже в любом проекте, но ты можешь переопределять правила его работы. Даже, если ты их не переопределял, то он все равно тебе выдает подсказки,  но они у тебя были проигнорированы. Смотри ниже:

- lowerCamelCase
Переменным не дается название с нижним подчеркиванием. Должны называться в таком формате [lowerCamelCase]
https://github.com/rn7cvj/todo_list/blob/242e2e98a6c8e25943d7fb27fb07af2e3cfcd86e/lib/modals/task.dart#L16-L18
[Подробнее]( https://dart-lang.github.io/linter/lints/non_constant_identifier_names.html)

- prefer_const_constructors
В некоторых местах можно явно указать, что виджет будет константным. Да, иногда не всегда это нужно делать. Но в данном случае думаю нужно было оставить const.
https://github.com/rn7cvj/todo_list/blob/242e2e98a6c8e25943d7fb27fb07af2e3cfcd86e/lib/pages/add_task_page/add_task_portrait.dart#L68
` duration: const Duration(milliseconds: 300), `
Подробнее: [Dart Documentation](https://dart-lang.github.io/linter/lints/non_constant_identifier_names.html)

- prefer_const_declarations
Используй const, вместо final, где это возможно. Константные конструкции определяются во время компиляции, а финальные при выполнении.
Подробнее:  [Dart Documentation](https://dart-lang.github.io/linter/lints/prefer_const_declarations.html)
Подробнее:  [Metanit]( https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&ved=2ahUKEwij7ZiQttz_AhV_AxAIHVdWCt4QFnoECA0QAw&url=https%3A%2F%2Fmetanit.com%2Fdart%2Ftutorial%2F2.2.php%23%3A~%3Atext%3D%25D0%2593%25D0%25BB%25D0%25B0%25D0%25B2%25D0%25BD%25D0%25BE%25D0%25B5%2520%25D1%2580%25D0%25B0%25D0%25B7%25D0%25BB%25D0%25B8%25D1%2587%25D0%25B8%25D0%25B5%2520%25D0%25BC%25D0%25B5%25D0%25B6%25D0%25B4%25D1%2583%2520const%2520%25D0%25B8%2Cfinal%2520%25D0%25BE%25D0%25BF%25D1%2580%25D0%25B5%25D0%25B4%25D0%25B5%25D0%25BB%25D1%258F%25D0%25B5%25D1%2582%25D1%2581%25D1%258F%2520%25D0%25B2%25D0%25BE%2520%25D0%25B2%25D1%2580%25D0%25B5%25D0%25BC%25D1%258F%2520%25D0%25B2%25D1%258B%25D0%25BF%25D0%25BE%25D0%25BB%25D0%25BD%25D0%25B5%25D0%25BD%25D0%25B8%25D1%258F.&usg=AOvVaw1lWATpoY346mGzz_le7nND&opi=89978449)

## 2. Форматирование кода. 
   В некоторых местах есть выходы кода за ограничение. Возможно ты делал autoformat, но это не помогало. 
   
- Запятая после переменной

https://github.com/rn7cvj/todo_list/blob/242e2e98a6c8e25943d7fb27fb07af2e3cfcd86e/lib/pages/add_task_page/add_task_portrait.dart#L61-L66 

Если поставим  `,` после `bottom: appPaddingMedium`, при автоформатировании это учтется и получится что-то такое:

```
 const Padding(
   padding: EdgeInsets.only(
      top: appPaddingMedium,
      bottom: appPaddingMedium,
   ),
   child: Divider(
      height: 2,
   ),
 ),
```

Вся информация про линтер и форматирование тут -> [Dart Documentation](https://dart.dev/guides/language/analysis-options#individual-rules)

Все остальное реализовано вроде прилично(Учитывая, что я не последователь GetIT и MobX)

## Придирки

Тут я опишу некоторые моменты, которы по моему мнению кажутся важными. (Можно игнорировать)

- Пакеты для маленьких задач.
Я бы не стал тянуть лишние пакеты, чтобы вызывать у них конкретную функциональность. С одной стороны я посмотрел и обновление пакета было недавно, но с другой стороны поддержка может прекратиться в любой момент. 
https://github.com/rn7cvj/todo_list/blob/242e2e98a6c8e25943d7fb27fb07af2e3cfcd86e/pubspec.yaml#L47

- Использование определенных хранилищ данных для определенных целей. 
Я бы не использовал get_storage, так как он предназначен для хранения каких-то маленьких данных, которые не нужно индексировать. В принципе они сами об это пишут в документации (в самом низу).
Иначе у тебя получаются вот такие ситуации, как ниже:

Тебе приходится перебирать все ключи и запоминать их значения, а потом по ним делать еще и запросы на получение значения. Теперь представь, что у тебя так миллион записей :).
https://github.com/rn7cvj/todo_list/blob/242e2e98a6c8e25943d7fb27fb07af2e3cfcd86e/lib/data/storage/storage.dart#L41-L56
Если бы это был, к примеру, sqlflie(SQL), то там бы вопрос решался одной строчкой `SELECT * from tasks where uuid == ...`

- Виджет тяжело переиспользовать.

У тебя есть виджет 
https://github.com/rn7cvj/todo_list/blob/242e2e98a6c8e25943d7fb27fb07af2e3cfcd86e/lib/pages/edit_task_page/widgets/delete_task_button.dart#L12-L17

И в самом низу ты определяешь для него логику нажатия

https://github.com/rn7cvj/todo_list/blob/242e2e98a6c8e25943d7fb27fb07af2e3cfcd86e/lib/pages/edit_task_page/widgets/delete_task_button.dart#L72-L77

Выходит так, что это виджет у тебя может делать только одно действие. А теперь представь ситуацию, когда тебе нужно точно такой же виджет показывать на другом экране, но с другой например кнопкой и логикой. Ты либо будешь новый виджет писать(копировать), либо можешь переделать этот так, что в качестве параметра он принимал метод `Function() deleteTask`

И таких виджетов, как я понял, у тебя несколько.

Как-то так) 

Итого. 
- Чистота кода и общая структура проекта (4б)
  форматирование: 0.5
  линт: 0.5
- State-Management (8)
- Получение и хранение данных (10)
- Разное (3)
Итого: 25

Если с чем-то не согласен - пиши, баллы еще не ставил

**Comment by rn7cvj** [comment]
> Привет, проверяю твое дз, постараюсь максимально подробно изложить все замечания и подкрепить их документацией.
> 
> ## 1. flutter_lints.
> Я вижу, что у тебя в зависимостях подтягивается flutter_lints. По умолчанию он настроен уже в любом проекте, но ты можешь переопределять правила его работы. Даже, если ты их не переопределял, то он все равно тебе выдает подсказки, но они у тебя были проигнорированы. Смотри ниже:
> 
> * lowerCamelCase
>   Переменным не дается название с нижним подчеркиванием. Должны называться в таком формате [lowerCamelCase]
>   https://github.com/rn7cvj/todo_list/blob/242e2e98a6c8e25943d7fb27fb07af2e3cfcd86e/lib/modals/task.dart#L16-L18
>   
>   [Подробнее](https://dart-lang.github.io/linter/lints/non_constant_identifier_names.html)
> * prefer_const_constructors
>   В некоторых местах можно явно указать, что виджет будет константным. Да, иногда не всегда это нужно делать. Но в данном случае думаю нужно было оставить const.
>   https://github.com/rn7cvj/todo_list/blob/242e2e98a6c8e25943d7fb27fb07af2e3cfcd86e/lib/pages/add_task_page/add_task_portrait.dart#L68
>   
>   `duration: const Duration(milliseconds: 300),`
>   Подробнее: [Dart Documentation](https://dart-lang.github.io/linter/lints/non_constant_identifier_names.html)
> * prefer_const_declarations
>   Используй const, вместо final, где это возможно. Константные конструкции определяются во время компиляции, а финальные при выполнении.
>   Подробнее:  [Dart Documentation](https://dart-lang.github.io/linter/lints/prefer_const_declarations.html)
>   Подробнее:  [Metanit](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&ved=2ahUKEwij7ZiQttz_AhV_AxAIHVdWCt4QFnoECA0QAw&url=https%3A%2F%2Fmetanit.com%2Fdart%2Ftutorial%2F2.2.php%23%3A~%3Atext%3D%25D0%2593%25D0%25BB%25D0%25B0%25D0%25B2%25D0%25BD%25D0%25BE%25D0%25B5%2520%25D1%2580%25D0%25B0%25D0%25B7%25D0%25BB%25D0%25B8%25D1%2587%25D0%25B8%25D0%25B5%2520%25D0%25BC%25D0%25B5%25D0%25B6%25D0%25B4%25D1%2583%2520const%2520%25D0%25B8%2Cfinal%2520%25D0%25BE%25D0%25BF%25D1%2580%25D0%25B5%25D0%25B4%25D0%25B5%25D0%25BB%25D1%258F%25D0%25B5%25D1%2582%25D1%2581%25D1%258F%2520%25D0%25B2%25D0%25BE%2520%25D0%25B2%25D1%2580%25D0%25B5%25D0%25BC%25D1%258F%2520%25D0%25B2%25D1%258B%25D0%25BF%25D0%25BE%25D0%25BB%25D0%25BD%25D0%25B5%25D0%25BD%25D0%25B8%25D1%258F.&usg=AOvVaw1lWATpoY346mGzz_le7nND&opi=89978449)
> 
> ## 2. Форматирование кода.
> В некоторых местах есть выходы кода за ограничение. Возможно ты делал autoformat, но это не помогало.
> 
> * Запятая после переменной
> 
> https://github.com/rn7cvj/todo_list/blob/242e2e98a6c8e25943d7fb27fb07af2e3cfcd86e/lib/pages/add_task_page/add_task_portrait.dart#L61-L66
> 
> Если поставим `,` после `bottom: appPaddingMedium`, при автоформатировании это учтется и получится что-то такое:
> 
> ```
>  const Padding(
>    padding: EdgeInsets.only(
>       top: appPaddingMedium,
>       bottom: appPaddingMedium,
>    ),
>    child: Divider(
>       height: 2,
>    ),
>  ),
> ```
> 
> Вся информация про линтер и форматирование тут -> [Dart Documentation](https://dart.dev/guides/language/analysis-options#individual-rules)
> 
> Все остальное реализовано вроде прилично(Учитывая, что я не последователь GetIT и MobX)
> 
> ## Придирки
> Тут я опишу некоторые моменты, которы по моему мнению кажутся важными. (Можно игнорировать)
> 
> * Пакеты для маленьких задач.
>   Я бы не стал тянуть лишние пакеты, чтобы вызывать у них конкретную функциональность. С одной стороны я посмотрел и обновление пакета было недавно, но с другой стороны поддержка может прекратиться в любой момент.
>   https://github.com/rn7cvj/todo_list/blob/242e2e98a6c8e25943d7fb27fb07af2e3cfcd86e/pubspec.yaml#L47
> * Использование определенных хранилищ данных для определенных целей.
>   Я бы не использовал get_storage, так как он предназначен для хранения каких-то маленьких данных, которые не нужно индексировать. В принципе они сами об это пишут в документации (в самом низу).
>   Иначе у тебя получаются вот такие ситуации, как ниже:
> 
> Тебе приходится перебирать все ключи и запоминать их значения, а потом по ним делать еще и запросы на получение значения. Теперь представь, что у тебя так миллион записей :).
> 
> https://github.com/rn7cvj/todo_list/blob/242e2e98a6c8e25943d7fb27fb07af2e3cfcd86e/lib/data/storage/storage.dart#L41-L56
> 
> 
> Если бы это был, к примеру, sqlflie(SQL), то там бы вопрос решался одной строчкой `SELECT * from tasks where uuid == ...`
> * Виджет тяжело переиспользовать.
> 
> У тебя есть виджет
> 
> https://github.com/rn7cvj/todo_list/blob/242e2e98a6c8e25943d7fb27fb07af2e3cfcd86e/lib/pages/edit_task_page/widgets/delete_task_button.dart#L12-L17
> 
> И в самом низу ты определяешь для него логику нажатия
> 
> https://github.com/rn7cvj/todo_list/blob/242e2e98a6c8e25943d7fb27fb07af2e3cfcd86e/lib/pages/edit_task_page/widgets/delete_task_button.dart#L72-L77
> 
> Выходит так, что это виджет у тебя может делать только одно действие. А теперь представь ситуацию, когда тебе нужно точно такой же виджет показывать на другом экране, но с другой например кнопкой и логикой. Ты либо будешь новый виджет писать(копировать), либо можешь переделать этот так, что в качестве параметра он принимал метод `Function() deleteTask`
> 
> И таких виджетов, как я понял, у тебя несколько.
> 
> Как-то так)
> 
> Итого.
> 
> * Чистота кода и общая структура проекта (4б)
>   форматирование: 0.5
>   линт: 0.5
> * State-Management (8)
> * Получение и хранение данных (10)
> * Разное (3)
>   Итого: 25
> 
> Если с чем-то не согласен - пиши, баллы еще не ставил

Привет спасибо большое за подробный разбор 🐳🐳🐳)

lowerCamelCase - имена полей берутся как ключи для конвертации в Json это можно изменить с помощью JsonKey но мне было лень т.к эти поля не используются, 
По поводу констант знаю, просто все упирается в то что у меня сейчас сессия и не получается всё успеть, 

Мелкий пакет для рестарта.
Нуууу я не знаю штука довольно нужна, и главная кросс платформенная, на самом деле перезапустить приложение из кода тот еще геморрой.

GetStorage
ахахаха это вообще мем, iasr не работает в вебе ( а мене это важно, все таки хочется залить веб демку на gh-pages) + у меня не получилось сделать универсальную модель, большинство баз данных требуют создание моделей путем аннотация, а у меня и так модель Task обвешена все чем только можно), так что я решил пусть просто храниться json и не буду лишний раз парится по поводу данных. Вообщем да косяк но это самый постой способ, и он работате.

По поводу ключей, мда просто там есть метод getValues который возвращает какую-то дич, по идее должен просто возвращаться список всех значение но он возвращает что угодно только не его.

По поводу переиспользования виджетов, я понимаю проблему но пока плохо представляю как впихнуть это в свое архитектуру, у меня не предполагается что экраны могут шарить между собой виджеты.

**Comment by dslmnvv** [comment]
Понял, тогда GetStorage или SharedPref подходят для кроссплатформенного использования более чем.

**Comment by MariyaViktorovna** [comment]
Привет!

В добавление к комментариям Диаса: можно разделить по разным файлам абстрактные классы и конкретные реализации.

За линт 0,5 балла
Итого: 25.5
